# Site settings
title: Universal Gravity
email: xiaojuzh AT gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning and exploring as scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juvion.github.io" # the base hostname & protocol for your site
twitter_username: juvion
github_username:  juvion

# Build settings
markdown: redcarpet
